/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRecommendationsRouteImport } from './routes/ai-recommendations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AiRecommendationsRecIdRouteImport } from './routes/ai-recommendations.$recId'
import { Route as AiRecommendationsRecIdLessonLessonIdRouteImport } from './routes/ai-recommendations.$recId.lesson.$lessonId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendationsRoute = AiRecommendationsRouteImport.update({
  id: '/ai-recommendations',
  path: '/ai-recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendationsRecIdRoute = AiRecommendationsRecIdRouteImport.update({
  id: '/$recId',
  path: '/$recId',
  getParentRoute: () => AiRecommendationsRoute,
} as any)
const AiRecommendationsRecIdLessonLessonIdRoute =
  AiRecommendationsRecIdLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AiRecommendationsRecIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-recommendations': typeof AiRecommendationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/ai-recommendations/$recId': typeof AiRecommendationsRecIdRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/ai-recommendations/$recId/lesson/$lessonId': typeof AiRecommendationsRecIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-recommendations': typeof AiRecommendationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/ai-recommendations/$recId': typeof AiRecommendationsRecIdRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/ai-recommendations/$recId/lesson/$lessonId': typeof AiRecommendationsRecIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-recommendations': typeof AiRecommendationsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/ai-recommendations/$recId': typeof AiRecommendationsRecIdRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/ai-recommendations/$recId/lesson/$lessonId': typeof AiRecommendationsRecIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-recommendations'
    | '/dashboard'
    | '/pricing'
    | '/ai-recommendations/$recId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/ai-recommendations/$recId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-recommendations'
    | '/dashboard'
    | '/pricing'
    | '/ai-recommendations/$recId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/ai-recommendations/$recId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/ai-recommendations'
    | '/dashboard'
    | '/pricing'
    | '/ai-recommendations/$recId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/ai-recommendations/$recId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRecommendationsRoute: typeof AiRecommendationsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommendations': {
      id: '/ai-recommendations'
      path: '/ai-recommendations'
      fullPath: '/ai-recommendations'
      preLoaderRoute: typeof AiRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommendations/$recId': {
      id: '/ai-recommendations/$recId'
      path: '/$recId'
      fullPath: '/ai-recommendations/$recId'
      preLoaderRoute: typeof AiRecommendationsRecIdRouteImport
      parentRoute: typeof AiRecommendationsRoute
    }
    '/ai-recommendations/$recId/lesson/$lessonId': {
      id: '/ai-recommendations/$recId/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/ai-recommendations/$recId/lesson/$lessonId'
      preLoaderRoute: typeof AiRecommendationsRecIdLessonLessonIdRouteImport
      parentRoute: typeof AiRecommendationsRecIdRoute
    }
  }
}

interface AiRecommendationsRecIdRouteChildren {
  AiRecommendationsRecIdLessonLessonIdRoute: typeof AiRecommendationsRecIdLessonLessonIdRoute
}

const AiRecommendationsRecIdRouteChildren: AiRecommendationsRecIdRouteChildren =
  {
    AiRecommendationsRecIdLessonLessonIdRoute:
      AiRecommendationsRecIdLessonLessonIdRoute,
  }

const AiRecommendationsRecIdRouteWithChildren =
  AiRecommendationsRecIdRoute._addFileChildren(
    AiRecommendationsRecIdRouteChildren,
  )

interface AiRecommendationsRouteChildren {
  AiRecommendationsRecIdRoute: typeof AiRecommendationsRecIdRouteWithChildren
}

const AiRecommendationsRouteChildren: AiRecommendationsRouteChildren = {
  AiRecommendationsRecIdRoute: AiRecommendationsRecIdRouteWithChildren,
}

const AiRecommendationsRouteWithChildren =
  AiRecommendationsRoute._addFileChildren(AiRecommendationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRecommendationsRoute: AiRecommendationsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
